### ISSUE TITLE
Accelerated Acquisition

### ISSUE THREAD

**Issue by srveale** [firasm/CEST#42]
I'll try to walk through this here, but the notebook CEST/simulation/Acc Factor might be good to look at.

First I plotted each component of magnetization, starting just after saturation finished. It was an off-resonance pulse so the magnetization was still close to equilibrium. Then the flip of 20 degrees around the y direction is applied, putting some of the z -magnetization into the x-direction. Free precession is allowed for 10 ms, then another flip, repeating like this for accfac = 72 times, producing a jagged exponential decay type curve. When Mz is small enough, T1 relaxation is fast enough to go back to the same level after each flip, and a steady state is reached.

The steady state should depend on T1 and the length of time between flips. It should not depend on the state of the magnetization just after saturation. 

![components during accelerated acq](https://cloud.githubusercontent.com/assets/7737922/8047011/f95c4c24-0df4-11e5-9952-27cac5cc2b94.png)

Next is a plot showing several z-spectra. The topmost curve corresponds to the first acquisition after the saturation, and the order continues downwards. CEST contrast is the highest for the first curve, as expected.
![z-spectra order after saturation pulse](https://cloud.githubusercontent.com/assets/7737922/8047031/468d6244-0df5-11e5-885e-b2a54f4969af.png)

Different weighting schemes could be used, depending on T1 and the time in between flips. Or, we could use the steady-state saturation to define T1.... Or we could use a known T1 to determine the best times between sequence pulses.

**Comment by firasm** [comment]
Very interesting - so here you've shown that if you take the "first k-space line" (first acquisition) after, it will produce a spectrum like the one in blue.

However if you wait 72x the first time, and use only the "last k-space line" (last acquisition), it will produce  a pretty flat spectrum.

@DrSAR, shouldn't we try to plot the average of all these lines from 1-72? That most closely matches the situation where we have acceleration...

**Comment by DrSAR** [comment]
Don't think that an average is an ideal way of looking at this. You lose too much information this way. I think one should possibly decide how much reduction of CEST effect you are prepared to accept (compared to the first line) and then, given relaxation and exchange rates, one can read off what acceleration factor will keep you above that level.

A detail just occurred to me: The acquisition that is being done here is using crushers. In other words, all transverse magnetization after a small flip is destroyed and we continue to only work with what's left in the longitudinal (z) direction. Is that what you are doing, @srveale ?

**Comment by srveale** [comment]
Yes, that's what's happening. I will try to work out the relation between relaxation and acceptable number of k-space lines.

**Comment by andrewcyung** [comment]
that's great work Scott.  To me, this illustrates that for every particular turbocest shot, we should try to first acquire the k-space line closest to k-space.  However, if we have multiple shots, then that means we have multiple saturation pulses, which you have not yet shown results for (all in due time).  Right now we are arranging the encodes in alternating reverse centric order, leaving the last shot to cover the most central part of k space (with the k-space centre being acquired last).  I think you've shown that for at least this last shot, it makes more sense to make sure the k-space center is acquired first.

As for the other central k-space lines, which makes more sense:

A) acquire during the last shot for maximum amount of saturation experienced, but run the risk of acquiring too long after the saturation pulse, or

B) put the line to be the first acquisition after saturation on an earlier shot, which might be bad because the total saturation time would be lower.

It sounds like an optimization problem that depends on T1 and the saturation pulse details.

One other issue to using multiple shots might be the risk of weighting the k-space data with a discontinuous function that is related to the t1 recovery during one shot.  It's easier to show you what I mean with a whiteboard, but I'm making an analogy to fast spin echo sequences where the t2 decay has a similar effect.  The end result may be ghosting or blurring.  I only mention this because I've been seeing a significant amount of smearing in some of my cest images.  I thought it was related to motion but maybe it's partly due to the multishot nature of the acquisition.

-Andrew

On Jun 8,o 2015,  at 4:55 PM,"srveale" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, that's what's happening. I will try to work out the relation between relaxation and acceptable number of k-space lines.

**Comment by DrSAR** [comment]
Assuming that we have an acceleration factor of k and are acquiring n lines of k-space and assuming further without loss of (too much) generality that n/k=4 I would suggest a scheme like this:

sat 0-4-8-12-... sat 1-5-9-13 ... sat 2-6-10-14 ... sat 3-7-11-15...

This will result in the highest CEST weighting in the centre gradually decreasing outwards.
Numbers indicate the line of k-space with 0 meaning centre. Ignore the fact that this is seemingly a k-space with only positive numbers (this can be extended to negative values). If the sat pulse is not very long, we might want to acquire the very centre later but I think it better be long such that first and second sat pulse isn't all that different (simulations to show when that occurs, please?). If it is an issue, one could minimize that effect by doing a partial inversion of the above like this:

sat 3-7-11-15... sat 2-6-10-14 ... sat 1-5-9-13 ...  sat 0-4-8-12- ... 

On a related note. We need that single- (or even multi-) shot EPI.

**Comment by andrewcyung** [comment]
Let me have a crack at programming the cest epi tomorrow.  When is firas back?  Looks like jen baker is on the schedule for Tuesday and Thursday.  Who is in charge of scanning?  This is for hpg?

On Jun 8, 2015, at 10:14 PM, "DrSAR" <notifications@github.com<mailto:notifications@github.com>> wrote:


Assuming that we have an acceleration factor of k and are acquiring n lines of k-space and assuming further without loss of (too much) generality that n/k=4 I would suggest a scheme like this:

sat 0-4-8-12-... sat 1-5-9-13 ... sat 2-6-10-14 ... sat 3-7-11-15...

This will result in the highest CEST weighting in the centre gradually decreasing outwards.
Numbers indicate the line of k-space with 0 meaning centre. Ignore the fact that this is seemingly a k-space with only positive numbers (this can be extended to negative values). If the sat pulse is not very long, we might want to acquire the very centre later but I think it better be long such that first and second sat pulse isn't all that different (simulations to show when that occurs, please?). If it is an issue, one could minimize that effect by doing a partial inversion of the above like this:

sat 3-7-11-15... sat 2-6-10-14 ... sat 1-5-9-13 ... sat 0-4-8-12- ...

On a related note. We need that single- (or even multi-) shot EPI.

**Comment by DrSAR** [comment]
Scott and I will be there. It'll be a busy DCE day I think.
S

**Comment by srveale** [comment]
I'm trying to illustrate how many acquisitions are possible for each saturation. Using plots similar to the second figure above, I determined the peak sizes for each acquisition. Those gold points are where the curves reduce to 50% their original value.
![peaksize order after sat pulse](https://cloud.githubusercontent.com/assets/7737922/8091385/6f1478b4-0f68-11e5-97ee-4fd9674752e1.png)

According to this metric, the number of acquisitions possible increases with increasing T1. The relation is:  number of acquisitions = 8.54*T1 + 21.4 (obviously rounded to an integer).

![higher t1 means more acquisitions](https://cloud.githubusercontent.com/assets/7737922/8091664/00444cfa-0f6a-11e5-8942-db205b4fb2b9.png)

This is just making the previous conclusions made in this issue a bit more quantifiable.
