### ISSUE TITLE
Detecting peaks in a more quantitative way

### ISSUE THREAD

**Issue by firasm** [firasm/CEST#49]
@andrewcyung has suggested a method to identify peaks by fitting a spline/polynomial to the baseline and then subtracting points from the spline and creating a plot of the difference from the peak and the baseline.

@srveale and I have done that, and here are the results for one scan from last Wednesday ("dCEST_brain.wk2/12")

![unknown](https://cloud.githubusercontent.com/assets/2507459/8389091/217ff096-1c20-11e5-9179-5d7593506b3c.png)

I'll update this with more details soon, and for the other scans

**Comment by firasm** [comment]
I think the most important thing to note here, is that the peak does appear to be "real" - in the noise area, it's red everywhere and inside the animal, the peak size is roughly 4%.

Here is the CEST spectrum for a single pixel analyzed using this method:

![unknown-4](https://cloud.githubusercontent.com/assets/2507459/8389291/e804eff8-1c22-11e5-84b0-b0e14369d0b9.png)

and here is the method applied to this pixel:

![unknown-5](https://cloud.githubusercontent.com/assets/2507459/8389295/fac81c96-1c22-11e5-9e12-bd668b7cd2d9.png)

Immediately we see that because the points near the peak were excluded, we should have acquired more points to better capture the baseline.

and here is the map of it pixel by pixel, as well as a water shift map as well (note the data aren't water shifted to 0 yet, so some of the offsets in the peak location map are to be expected):

![unknown-3](https://cloud.githubusercontent.com/assets/2507459/8389283/be290566-1c22-11e5-82d3-d1d275005b1f.png)

## Note: At the moment I'm only looking at the peak around 2 ppm (because it's larger), not the 3.5 ppm one.

**Comment by DrSAR** [comment]
mh - interesting what you say about higher resolution. It's probably true that it would be good to have at least 3 maybe 5 points defining a peak. This, of course, assumes you got the frequency right. It might be more time-efficient to acquire enough water and enough near 2 (or 3.5)ppm and then shift, before the spline fit. 

But in general, the map looks decent. Also, the plot with fit that you have shown above is probably what would be nice in a VTC-style display.

**Comment by andrewcyung** [comment]
Can you try a polynomial or spline fit of lower order?  Some way to reduce the weight of the cest peaks during fitting?

On Jun 26, 2015, at 4:49 PM, "firasm" <notifications@github.com<mailto:notifications@github.com>> wrote:


I think the most important thing to note here, is that the peak does appear to be "real" - in the noise area, it's red everywhere and inside the animal, the peak size is roughly 4%.

Here is the CEST spectrum for a single pixel analyzed using this method:

[unknown-4]<https://cloud.githubusercontent.com/assets/2507459/8389291/e804eff8-1c22-11e5-84b0-b0e14369d0b9.png>

and here is the method applied to this pixel:

[unknown-5]<https://cloud.githubusercontent.com/assets/2507459/8389295/fac81c96-1c22-11e5-9e12-bd668b7cd2d9.png>

Immediately we see that because the points near the peak were excluded, we should have acquired more points to better capture the baseline.

and here is the map of it pixel by pixel, as well as a water shift map as well (note the data aren't water shifted to 0 yet, so some of the offsets in the peak location map are to be expected):

[unknown-3]<https://cloud.githubusercontent.com/assets/2507459/8389283/be290566-1c22-11e5-82d3-d1d275005b1f.png>

Note: At the moment I'm only looking at the peak around 2 ppm (because it's larger), not the 3.5 ppm one.

**Comment by firasm** [comment]
I did do a polynomial fit, it's of order 5 and I tried as low as 3. 




The cest peak points were actually removed to fit the polynomial (which is what I meant by needed more points to fit the baseline)

**Comment by firasm** [comment]
In commit 6ad6350, I have implemented the water shift feature, maps for last days experiment coming soon. closing this issue
